tosca_definitions_version: cloudify_dsl_1_2

plugins:
  mist:
    executor: central_deployment_agent
    source: "https://github.com/mistio/cloudify-mist-plugin/archive/master.zip"

data_types:
  cloudify.datatypes.mist.Config:
    properties:
      mist_token:
          description: an input for the test
          default: ''
      mist_uri:
          type: string
          default: https://mist.io
  cloudify.datatypes.mist.MachineParams:
    properties:
      machine_id:
          type: string
          default: ''
      cloud_id:
          type: string
          default: ''
      name:
          type: string
          default: ''
      key_id:
          type: string
          default: ''
      image_id:
          type: string
          default: ''
      size_id:
          type: string
          default: ''
      location_id:
          type: string
          default: ''
      network_id:
          type: string
          default: ''
      location_name:
          type: string
          default: ''
      image_extra:
          type: string
          default: ''
      disk:
          type: string
          default: ''
      script:
          type: string
          default: ''
      monitoring:
          type: boolean
          default: false
      ips:
          default: []
      #networks:
      #    default: []
      docker_command:
          type: string
          default: ''
      script_id:
          type: string
          default: ''
      script_params:
          type: string
          default: ''
      #provider:
      #    type: string
      #    default: ''
      associate_floating_ip:  # TODO not used?
          default: true
      tags:
          default: {}


node_types:
  cloudify.mist.nodes.KeyPair:
    derived_from: cloudify.nodes.Root
    properties:
      install_agent:
        default: false
      use_external_resource:
        description: >
          Indicate whether the resource exists or if Cloudify should create the resource.
        type: boolean
        default: false
      resource_id:
        description: >
          Either the name or ID of the resource in Cloudify. If this is an existing
          resource, you should provide the name or the ID of the resource in Amazon AWS.
        type: string
        default: ''
      private_key_path:
        description: >
          The path where the key should be saved on the machine. If this is a bootstrap
          process, this refers to the local computer. If this will run on the manager,
          this will be saved on the manager.
        type: string
        default: ''
      parameters:
        description: >
          The key value pair parameters required by Mist Client to use
          the mist.client.backend.create_machine command.(backend_id,image_id
          size_id, location_id, name, monitoring, ssh_user, networks)
        default: {}
      mist_config:
        description: >
          A dictionary of values to pass to authenticate with the Mist API.
        type: cloudify.datatypes.mist.Config
    interfaces:
      cloudify.interfaces.lifecycle:
        create: mist.plugin.keypair.create
        delete: mist.plugin.keypair.delete
      cloudify.interfaces.validation:
        creation: mist.plugin.keypair.creation_validation

  cloudify.mist.nodes.Server:
    derived_from: cloudify.nodes.Compute
    properties:
      install_agent:
        default: false
      use_external_resource:
        description: >
          Indicate whether the resource exists or if Cloudify should create the resource.
        type: boolean
        default: false
      resource_id:
        description: >
          Either the name or ID of the resource in Cloudify. If this is an existing
          resource, you should provide the name or the ID of the resource in Mist.io.
        type: string
        default: ''
      parameters:
        description: >
          The key value pair parameters required by Mist Client to use
          the mist.client.backend.create_machine command.(backend_id,image_id
          size_id, location_id, name, monitoring, ssh_user, networks )
        type: cloudify.datatypes.mist.MachineParams
      mist_config:
        description: >
          A dictionary of values to pass to authenticate with the Mist API.
        type: cloudify.datatypes.mist.Config
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: mist.plugin.server.create
          inputs:
            use_external_resource:
              default: false
            mist_config:
              default: {}
        start:
          implementation: mist.plugin.server.start
          inputs:
            start_retry_interval:
              description: Polling interval until the server is active in seconds
              type: integer
              default: 30
        stop:
          implementation: mist.plugin.server.stop
          inputs:
            mist_config:
              default: {}
        delete:
          implementation: mist.plugin.server.delete
          inputs:
            mist_config:
              default: {}
      cloudify.interfaces.validation:
        creation:
          implementation: mist.plugin.server.creation_validation
          inputs:
            args:
              default: {}

  cloudify.mist.nodes.Network:
    derived_from: cloudify.nodes.Network
    properties:
      install_agent:
        default: false
      use_external_resource:
        description: >
          Indicate whether the resource exists or if Cloudify should create the resource.
        type: boolean
        default: false
      resource_id:
        description: >
          Either the name or ID of the resource in Cloudify. If this is an existing
          resource, you should provide the name or the ID of the resource in Mist.io.
        type: string
        default: ''
      parameters:
        description: >
          The key value pair parameters required by Mist Client to use
          the mist.client.cloud.create_network command.(
          {"network":{"name":"testnet","admin_state_up":true},
          "subnet":{"name":"happy_subnet","ip_version":"4","cidr":"",
          "gateway_ip":"","enable_dhcp":true,
          "allocation_pools":[{"start":"","end":""}]}}: )
        default: {}
      mist_config:
        description: >
          A dictionary of values to pass to authenticate with the Mist API.
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: mist.plugin.network.create
        delete:
          implementation: mist.plugin.network.delete


relationships:
  cloudify.mist.relationships.server_connected_to_keypair:
    derived_from: cloudify.relationships.connected_to
  cloudify.mist.relationships.server_connected_to_network:
    derived_from: cloudify.relationships.depends_on
    target_interfaces:
      cloudify.interfaces.relationship_lifecycle:
        preconfigure:
          implementation: mist.plugin.network.associate_network
          inputs:
            ip:
              default: ''
            assign:
              default: true
